# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

- task: Maven@3
  displayName: MandatoryTestsRun
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -DrunSuite=**/*.java -Dtests123=Mandatory'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    
 steps:
- task: Maven@3
  displayName: NonMandatoryTestsRun
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -DrunSuite=**/*.java -Dtests123=NonMandatory1,NonMandatory2 -Dmaven.test.failure.ignore=true -DtestFailureIgnore=true'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'